# Имя воркфлоу
name: Automated Branch Protector

# Запускать только вручную (самый безопасный вариант)
on:
  workflow_dispatch:

jobs:
  protect-all-repositories:
    # Запускаем на стандартном сервере GitHub
    runs-on: ubuntu-latest
    
    steps:
      # Этот шаг — единственный. Вся магия внутри него.
      - name: Find Repos and Apply Protection
        env:
          # Ваш токен, который вы уже добавили в секреты
          GITHUB_TOKEN: ${{ secrets.PAT }}
          # Ваш логин на GitHub, определяется автоматически
          GITHUB_USER: ${{ github.repository_owner }}
        
        # Этот скрипт выполнит всю работу
        run: |
          # 1. Получаем список всех ваших репозиториев
          # Используем 'jq' - стандартный инструмент на серверах GitHub для работы с JSON
          # Он отфильтрует архивированные репозитории и сам репозиторий .github
          REPO_NAMES=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/users/$GITHUB_USER/repos?type=owner&per_page=100" | \
            jq -r '.[] | select(.archived==false and .name!=".github") | .name')

          # 2. Готовим правила защиты в виде переменной
          JSON_PAYLOAD=$(cat <<'EOF'
          {
            "enforce_admins": true,
            "required_pull_request_reviews": {
              "required_approving_review_count": 1,
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": false
            },
            "required_status_checks": null,
            "restrictions": null,
            "allow_force_pushes": false,
            "allow_deletions": false
          }
          EOF
          )

          echo "Найдено репозиториев для обработки:"
          echo "$REPO_NAMES"
          echo "-------------------------------------"

          # 3. Проходим по каждому репозиторию в списке
          for REPO in $REPO_NAMES; do
            echo "--- Обработка репозитория: $REPO ---"
            
            # Проверяем, существует ли в нём ветка 'main'
            BRANCH_CHECK_CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$GITHUB_USER/$REPO/branches/main")
            
            if [ "$BRANCH_CHECK_CODE" = "200" ]; then
              echo "Ветка 'main' найдена. Применяем защиту..."
              
              # Отправляем запрос на установку защиты
              PROTECT_RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X PUT \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                -d "$JSON_PAYLOAD" \
                "https://api.github.com/repos/$GITHUB_USER/$REPO/branches/main/protection")
              
              if [ "$PROTECT_RESPONSE_CODE" = "200" ]; then
                echo "✅ УСПЕХ: Защита для '$REPO' успешно применена."
              else
                echo "❌ ОШИБКА: Не удалось применить защиту для '$REPO'. Код ответа GitHub: $PROTECT_RESPONSE_CODE."
              fi
            else
              echo "➡️ ПРОПУСК: Ветка 'main' в репозитории '$REPO' не найдена."
            fi
          done
