# Имя воркфлоу
name: Automated Branch Protector

# Условия запуска
on:
  schedule:
        - cron: '0 */18 * * *'
  workflow_dispatch:


jobs:
  protect-all-repositories:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Основная логика поиска и защиты веток
      - name: Find Repos, Branches and Apply Protection
        # Даем этому шагу ID, чтобы следующий шаг мог использовать его результаты
        id: protection_step
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GITHUB_USER: ${{ github.repository_owner }}
          PROTECTION_RULES: |
            {
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "required_approving_review_count": 1,
                "dismiss_stale_reviews": true
              },
              "required_status_checks": null,
              "restrictions": null,
              "allow_force_pushes": false,
              "allow_deletions": false
            }
        run: |
          # Инициализируем переменные-счетчики для будущего отчета
          protected_list=""
          skipped_count=0
          newly_protected_count=0
          error_count=0
          
          echo "Шаг 1: Получение списка репозиториев..."
          API_RESPONSE_FILE=$(mktemp)
          HTTP_STATUS=$(curl -s -w "%{http_code}" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/users/$GITHUB_USER/repos?type=owner&per_page=100" \
            -o $API_RESPONSE_FILE)

          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "❌ КРИТИЧЕСКАЯ ОШИБКА: Не удалось получить список репозиториев. Код ответа: $HTTP_STATUS"
            cat $API_RESPONSE_FILE
            exit 1
          fi

          echo "✅ Список репозиториев успешно получен."
          REPO_NAMES=$(cat $API_RESPONSE_FILE | jq -r '.[] | select(.archived==false and .name!=".github") | .name')
          rm $API_RESPONSE_FILE

          # --- ВСЯ ПРЕДЫДУЩАЯ ЛОГИКА ОСТАЕТСЯ НА МЕСТЕ ---
          for REPO in $REPO_NAMES; do
            echo "-------------------------------------"
            echo "--- Обработка репозитория: $REPO ---"
            
            BRANCHES_API_RESPONSE_FILE=$(mktemp)
            BRANCHES_HTTP_STATUS=$(curl -s -w "%{http_code}" \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$GITHUB_USER/$REPO/branches" \
              -o $BRANCHES_API_RESPONSE_FILE)

            if [ "$BRANCHES_HTTP_STATUS" -ne 200 ]; then
              echo "⚠️ ПРЕДУПРЕЖДЕНИЕ: Не удалось получить список веток для '$REPO'. Код: $BRANCHES_HTTP_STATUS."
              error_count=$((error_count+1))
              rm $BRANCHES_API_RESPONSE_FILE
              continue
            fi

            # ИЗМЕНЕНИЕ: Получаем только ветку 'main'
            BRANCH_NAMES=$(cat $BRANCHES_API_RESPONSE_FILE | jq -r '.[] | select(.name=="main") | .name')
            rm $BRANCHES_API_RESPONSE_FILE

            if [ -z "$BRANCH_NAMES" ]; then
              echo "➡️ ПРОПУСК: В репозитории '$REPO' не найдено ветки 'main'."
              continue
            fi
            
            for BRANCH in $BRANCH_NAMES; do
              echo " - Проверка ветки: '$BRANCH'..."
              PROTECTION_CHECK_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
                -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/$GITHUB_USER/$REPO/branches/$BRANCH/protection")

              if [ "$PROTECTION_CHECK_CODE" = "200" ]; then
                echo " ✅ ПРОПУСК: Ветка '$BRANCH' уже защищена."
                skipped_count=$((skipped_count+1))
              elif [ "$PROTECTION_CHECK_CODE" = "404" ]; then
                echo " ⏳ ПРИМЕНЕНИЕ ЗАЩИТЫ для ветки '$BRANCH'..."
                APPLY_PROTECTION_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X PUT \
                  -H "Authorization: token $GITHUB_TOKEN" \
                  -d "$PROTECTION_RULES" \
                  "https://api.github.com/repos/$GITHUB_USER/$REPO/branches/$BRANCH/protection")

                if [ "$APPLY_PROTECTION_CODE" = "200" ]; then
                  echo " ✅ УСПЕХ: Защита для ветки '$BRANCH' успешно применена."
                  protected_list="$protected_list\n- \`$REPO\` / \`$BRANCH\`"
                  newly_protected_count=$((newly_protected_count+1))
                else
                  echo " ❌ ОШИБКА: Не удалось применить защиту для '$BRANCH'. Код: $APPLY_PROTECTION_CODE."
                  error_count=$((error_count+1))
                fi
              else
                echo " ❌ ОШИБКА: Не удалось проверить статус защиты для '$BRANCH'. Код: $PROTECTION_CHECK_CODE."
                error_count=$((error_count+1))
              fi
            done
          done

          # --- ДОБАВЛЕННЫЙ ФРАГМЕНТ: Сохраняем результаты для следующего шага --
          echo "protected_list<<EOF" >> $GITHUB_OUTPUT
          echo -e "$protected_list" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "skipped_count=$skipped_count" >> $GITHUB_OUTPUT
          echo "newly_protected_count=$newly_protected_count" >> $GITHUB_OUTPUT
          echo "error_count=$error_count" >> $GITHUB_OUTPUT

      # Шаг 2: Новый шаг, который генерирует красивый отчет
      - name: Generate Job Summary
        # `if: always()` гарантирует, что отчет создастся, даже если предыдущий шаг завершился с ошибкой
        if: always()
        run: |
          echo "### 🛡️ Отчет о работе Automated Branch Protector" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Красивая таблица со статистикой
          echo "| Статус | Количество |" >> $GITHUB_STEP_SUMMARY
          echo "|:---|:---|" >> $GITHUB_STEP_SUMMARY
          echo "| ✅ Новая защита применена | **${{ steps.protection_step.outputs.newly_protected_count }}** |" >> $GITHUB_STEP_SUMMARY
          echo "| ➡️ Пропущено (уже защищены) | **${{ steps.protection_step.outputs.skipped_count }}** |" >> $GITHUB_STEP_SUMMARY
          echo "| ❌ Обнаружено ошибок | **${{ steps.protection_step.outputs.error_count }}** |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Если были применены новые защиты, выводим их список
          if [ "${{ steps.protection_step.outputs.newly_protected_count }}" -gt 0 ]; then
            echo "---" >> $GITHUB_STEP_SUMMARY
            echo "#### Детализация примененных защит:" >> $GITHUB_STEP_SUMMARY
            echo "${{ steps.protection_step.outputs.protected_list }}" >> $GITHUB_STEP_SUMMARY
          # Если ничего не делали, сообщаем об этом
          elif [ "${{ steps.protection_step.outputs.newly_protected_count }}" -eq 0 ] && [ "${{ steps.protection_step.outputs.error_count }}" -eq 0 ]; then
            echo "> Никаких действий не потребовалось. Все найденные ветки 'main' уже были под защитой." >> $GITHUB_STEP_SUMMARY
          fi